/* AUTO-GENERATED by @rtp/canvas-core — kind: agents
 * Regenerate with: ./rtpsc canvas create agents
 * Do not hand-edit the STATE literal; template body may be customized carefully.
 */
import {
  Card,
  CardBody,
  CardHeader,
  Divider,
  Grid,
  H1,
  H2,
  Pill,
  Row,
  Stack,
  Stat,
  Table,
  Text
} from 'cursor/canvas';

const STATE = {
  "kind": "agents",
  "title": "RTPSC Development Team",
  "company": "Ross Tax Pro Software Co",
  "application": "Efile Transmission Software",
  "abbreviation": "RTPSC",
  "generatedAt": "2026-07-26T08:47:34.490Z",
  "teamCount": 7,
  "team": [
    {
      "role": "planning-agent",
      "title": "Planning",
      "focus": "phased delivery plan, milestones & exit criteria"
    },
    {
      "role": "scoping-agent",
      "title": "Scoping",
      "focus": "inventory, complexity index & scope boundaries"
    },
    {
      "role": "testing-agent",
      "title": "Testing / Validation / Verification",
      "focus": "invariants, validations & verifications"
    },
    {
      "role": "mapping-agent",
      "title": "Mapping & Enhancement",
      "focus": "dependency map & enhancement recommendations"
    },
    {
      "role": "staging-agent",
      "title": "Staging",
      "focus": "staged rollout, promotion & gates"
    },
    {
      "role": "assessment-agent",
      "title": "Environmental Assessment & Inspection",
      "focus": "environment, safeguards & findings"
    },
    {
      "role": "markdown-agent",
      "title": "Markdown Generation Engine",
      "focus": "documentation generation"
    }
  ],
  "note": "Agents are deployment-assist & development tooling — not a runtime product subsystem."
} as const;

export default function AgentsCanvas() {
  return (
    <Stack gap={20} style={{ padding: 24 }}>
      <Stack gap={6}>
        <Text tone="secondary" size="small">{STATE.company}</Text>
        <H1>{STATE.title}</H1>
        <Row gap={8} align="center">
          <Pill tone="info">{STATE.teamCount} agents</Pill>
          <Text tone="secondary" size="small">{STATE.generatedAt}</Text>
        </Row>
        <Text>{STATE.note}</Text>
      </Stack>

      <Divider />

      <Stack gap={12}>
        {STATE.team.map((member) => (
          <Card key={member.role}>
            <CardHeader title={member.title} trailing={<Pill tone="neutral">{member.role}</Pill>} />
            <CardBody>
              <Text>{member.focus}</Text>
            </CardBody>
          </Card>
        ))}
      </Stack>
    </Stack>
  );
}
