/* AUTO-GENERATED by @rtp/canvas-core — kind: compliance
 * Regenerate with: ./rtpsc canvas create compliance
 * Do not hand-edit the STATE literal; template body may be customized carefully.
 */
import {
  Card,
  CardBody,
  CardHeader,
  Divider,
  Grid,
  H1,
  H2,
  Pill,
  Row,
  Stack,
  Stat,
  Table,
  Text
} from 'cursor/canvas';

const STATE = {
  "kind": "compliance",
  "title": "RTPSC Compliance Posture",
  "company": "Ross Tax Pro Software Co",
  "application": "Efile Transmission Software",
  "abbreviation": "RTPSC",
  "generatedAt": "2026-07-26T08:47:34.489Z",
  "environment": {
    "appEnv": "local",
    "protected": true,
    "transmissionAllowed": false,
    "safeguards": {
      "productionEnvironment": false,
      "secretsConfigured": false,
      "approvedTunnel": false,
      "transmissionFlagEnabled": false
    },
    "reasons": [
      "Environment \"local\" is not a production environment.",
      "API/TDS/tunnel secrets are not fully configured.",
      "No approved secure tunnel endpoint is configured.",
      "EFILE_TRANSMISSION_ENABLED is not set to \"true\"."
    ]
  },
  "gates": [
    {
      "id": "env-protection",
      "label": "Environment protection",
      "status": "blocked",
      "detail": "Transmission stays blocked until production safeguards pass."
    },
    {
      "id": "secrets",
      "label": "Secrets posture",
      "status": "scaffold",
      "detail": "Client IDs/secrets and tunnel credentials remain environment-based only."
    },
    {
      "id": "compliance-report",
      "label": "Production compliance report",
      "status": "ready_scaffold",
      "detail": "Expect overall ready_scaffold until manual legal/security/ops sign-offs."
    },
    {
      "id": "ai-boundaries",
      "label": "AI persona boundaries",
      "status": "enforced",
      "detail": "AI cannot sign, transmit, or clear material HOLD (RTP-AI-001)."
    }
  ]
} as const;

function gateTone(status: string): 'neutral' | 'info' | 'success' | 'warning' | 'danger' {
  switch (status) {
    case 'clear':
    case 'configured':
    case 'enforced':
      return 'success';
    case 'ready_scaffold':
    case 'scaffold':
      return 'info';
    case 'blocked':
      return 'warning';
    default:
      return 'neutral';
  }
}

export default function ComplianceCanvas() {
  return (
    <Stack gap={20} style={{ padding: 24 }}>
      <Stack gap={6}>
        <Text tone="secondary" size="small">{STATE.company}</Text>
        <H1>{STATE.title}</H1>
        <Text tone="secondary" size="small">
          Scaffold readiness · {STATE.generatedAt}
        </Text>
      </Stack>

      <Grid columns={3} gap={12}>
        <Stat label="App env" value={String(STATE.environment.appEnv)} />
        <Stat
          label="Transmission"
          value={STATE.environment.transmissionAllowed ? 'allowed' : 'blocked'}
        />
        <Stat label="Protected" value={STATE.environment.protected ? 'yes' : 'no'} />
      </Grid>

      <Divider />

      <Stack gap={12}>
        <H2>Gates</H2>
        <Grid columns={2} gap={12}>
          {STATE.gates.map((gate) => (
            <Card key={gate.id}>
              <CardHeader
                title={gate.label}
                trailing={<Pill tone={gateTone(gate.status)}>{gate.status}</Pill>}
              />
              <CardBody>
                <Text>{gate.detail}</Text>
              </CardBody>
            </Card>
          ))}
        </Grid>
      </Stack>

      <Stack gap={8}>
        <H2>Open protection reasons</H2>
        {STATE.environment.reasons.length === 0 ? (
          <Text>None.</Text>
        ) : (
          STATE.environment.reasons.map((reason, index) => (
            <Text key={index}>• {reason}</Text>
          ))
        )}
      </Stack>
    </Stack>
  );
}
