/* AUTO-GENERATED by @rtp/canvas-core — kind: modules
 * Regenerate with: ./rtpsc canvas create modules
 * Do not hand-edit the STATE literal; template body may be customized carefully.
 */
import {
  Card,
  CardBody,
  CardHeader,
  Divider,
  Grid,
  H1,
  H2,
  Pill,
  Row,
  Stack,
  Stat,
  Table,
  Text
} from 'cursor/canvas';

const STATE = {
  "kind": "modules",
  "title": "RTPSC Module Catalog",
  "company": "Ross Tax Pro Software Co",
  "application": "Efile Transmission Software",
  "abbreviation": "RTPSC",
  "generatedAt": "2026-07-26T08:47:34.490Z",
  "totalModules": 34,
  "categories": [
    {
      "category": "packages",
      "description": "Shared libraries and runtime primitives.",
      "count": 13,
      "modules": [
        {
          "name": "@rtp/platform-core",
          "summary": "Runtime config, HTTP/worker helpers, and descriptor factories.",
          "tags": [
            "runtime",
            "shared"
          ],
          "dependsOn": []
        },
        {
          "name": "@rtp/client-config",
          "summary": "API/TDS/tunnel credential placeholders and governance notes.",
          "tags": [
            "config"
          ],
          "dependsOn": []
        },
        {
          "name": "@rtp/client-identity",
          "summary": "Full API + TDS client id issuance, authentication, scopes, and auth audit logging.",
          "tags": [
            "identity",
            "api-client",
            "tds-client"
          ],
          "dependsOn": []
        },
        {
          "name": "@rtp/refund-core",
          "summary": "Full refund cases, approved-event ingest, pipeline stages, workflow + intelligence.",
          "tags": [
            "refund",
            "pipeline",
            "intelligence"
          ],
          "dependsOn": []
        },
        {
          "name": "@rtp/secure-tunnel",
          "summary": "Compliant secure tunnel adapter interface (stub-safe).",
          "tags": [
            "compliance"
          ],
          "dependsOn": []
        },
        {
          "name": "@rtp/workflow-engine",
          "summary": "Modular task/workflow/trigger engine with run history.",
          "tags": [
            "workflow",
            "engine"
          ],
          "dependsOn": []
        },
        {
          "name": "@rtp/bank-products",
          "summary": "SBTPG products, login clearance/audit logging, disclosures, and the fail-safe payment gate.",
          "tags": [
            "bank-products",
            "sbtpg",
            "auth",
            "audit"
          ],
          "dependsOn": []
        },
        {
          "name": "@rtp/tax-data",
          "summary": "State and county/parish taxation reference data for invoicing calculations.",
          "tags": [
            "tax",
            "jurisdiction",
            "parish"
          ],
          "dependsOn": []
        },
        {
          "name": "@rtp/invoice-core",
          "summary": "Invoicing machine core: AI data entry, tax calc, payment approval/confirmation, PDF & receipt export.",
          "tags": [
            "invoicing",
            "ai-assist",
            "pdf",
            "receipt"
          ],
          "dependsOn": []
        },
        {
          "name": "@rtp/crm-core",
          "summary": "CRM contacts, household accounts, and interaction timeline for tax-prep operations.",
          "tags": [
            "crm",
            "contacts"
          ],
          "dependsOn": []
        },
        {
          "name": "@rtp/pos-core",
          "summary": "Point of Sale sessions/carts that check out through invoice-core and link sales back to CRM.",
          "tags": [
            "pos",
            "checkout",
            "crm-linked"
          ],
          "dependsOn": [
            "@rtp/crm-core",
            "@rtp/invoice-core",
            "@rtp/tax-data"
          ]
        },
        {
          "name": "@rtp/ero-ops",
          "summary": "SBTPG report tracing, automated ERO phrasing, and refund-intelligence scoring.",
          "tags": [
            "ero",
            "sbtpg",
            "refund-intelligence"
          ],
          "dependsOn": []
        },
        {
          "name": "@rtp/canvas-core",
          "summary": "Cursor Canvas creation — generate .canvas.tsx artifacts from live platform state.",
          "tags": [
            "canvas",
            "cursor",
            "devtools"
          ],
          "dependsOn": []
        }
      ]
    },
    {
      "category": "services",
      "description": "HTTP service surfaces.",
      "count": 8,
      "modules": [
        {
          "name": "api-gateway",
          "summary": "Authenticate API client id/secret at the ingress edge.",
          "tags": [
            "ingress",
            "port:3000"
          ],
          "dependsOn": []
        },
        {
          "name": "refund-status-service",
          "summary": "Ingest refund status events from approved sources only (no scraping).",
          "tags": [
            "refund-status",
            "port:3001"
          ],
          "dependsOn": []
        },
        {
          "name": "transcript-service",
          "summary": "Coordinate account transcript pull requests.",
          "tags": [
            "transcripts",
            "port:3002"
          ],
          "dependsOn": []
        },
        {
          "name": "analytics-service",
          "summary": "Aggregate refund intelligence and analytics center outputs.",
          "tags": [
            "analytics",
            "port:3003"
          ],
          "dependsOn": []
        },
        {
          "name": "enrollment-service",
          "summary": "Expose SBTPG refund advance / refund transfer products and disclosures.",
          "tags": [
            "bank-products",
            "port:3004"
          ],
          "dependsOn": []
        },
        {
          "name": "invoice-service",
          "summary": "Run the invoicing machine for tax-prep operations (create, approve, pay).",
          "tags": [
            "operations",
            "port:3005"
          ],
          "dependsOn": []
        },
        {
          "name": "pos-crm-service",
          "summary": "Operate the CRM for tax-prep clients (contacts, accounts, interactions).",
          "tags": [
            "operations",
            "port:3006"
          ],
          "dependsOn": []
        },
        {
          "name": "modules-dashboard",
          "summary": "Serve a read-only catalog of every platform module.",
          "tags": [
            "operations",
            "port:3010"
          ],
          "dependsOn": []
        }
      ]
    },
    {
      "category": "workers",
      "description": "Background processes (including the workflow runner).",
      "count": 4,
      "modules": [
        {
          "name": "tds-worker",
          "summary": "Authenticate with a full TDS client id/secret before any pull job.",
          "tags": [
            "always-on",
            "long-running"
          ],
          "dependsOn": []
        },
        {
          "name": "transcript-pull-worker",
          "summary": "Coordinate approved account transcript pulls.",
          "tags": [
            "always-on",
            "long-running"
          ],
          "dependsOn": []
        },
        {
          "name": "live-source-fetcher",
          "summary": "Poll or subscribe to approved live sources only.",
          "tags": [
            "always-on",
            "long-running"
          ],
          "dependsOn": []
        },
        {
          "name": "workflow-runner",
          "summary": "Runs all modular workflows in the background (schedules + events).",
          "tags": [
            "always-on",
            "background"
          ],
          "dependsOn": []
        }
      ]
    },
    {
      "category": "pipelines",
      "description": "Staged data processing definitions.",
      "count": 3,
      "modules": [
        {
          "name": "transmission-pipeline",
          "summary": "5 stages → 3 outputs",
          "tags": [
            "pipeline"
          ],
          "dependsOn": []
        },
        {
          "name": "masterfile-pipeline",
          "summary": "4 stages → 2 outputs",
          "tags": [
            "pipeline"
          ],
          "dependsOn": []
        },
        {
          "name": "refund-status-pipeline",
          "summary": "4 stages → 2 outputs",
          "tags": [
            "pipeline"
          ],
          "dependsOn": []
        }
      ]
    },
    {
      "category": "engines",
      "description": "Analytical and intelligence engines.",
      "count": 3,
      "modules": [
        {
          "name": "refund-intelligence-engine",
          "summary": "8 capabilities",
          "tags": [
            "engine"
          ],
          "dependsOn": []
        },
        {
          "name": "analytics-center",
          "summary": "3 capabilities",
          "tags": [
            "engine"
          ],
          "dependsOn": []
        },
        {
          "name": "tc-code-engine",
          "summary": "3 capabilities",
          "tags": [
            "engine"
          ],
          "dependsOn": []
        }
      ]
    },
    {
      "category": "workflows",
      "description": "Modular workflow definitions (executed by the background workflow-runner).",
      "count": 3,
      "modules": [
        {
          "name": "refund-status-update",
          "summary": "Normalize a refund request, evaluate status, score risk, and emit an update event.",
          "tags": [
            "event:refund.status.received",
            "refund",
            "event-driven"
          ],
          "dependsOn": []
        },
        {
          "name": "transcript-intake",
          "summary": "Validate authorization, normalize transcript products, and package a TDS packet.",
          "tags": [
            "manual",
            "transcript",
            "manual",
            "authorization-gated"
          ],
          "dependsOn": []
        },
        {
          "name": "transmission-cycle",
          "summary": "Prepare, validate, queue, transmit (stub-safe), and acknowledge a transmission batch.",
          "tags": [
            "schedule:60s",
            "transmission",
            "scheduled"
          ],
          "dependsOn": []
        }
      ]
    }
  ]
} as const;

export default function ModulesCanvas() {
  return (
    <Stack gap={20} style={{ padding: 24 }}>
      <Stack gap={6}>
        <Text tone="secondary" size="small">{STATE.company}</Text>
        <H1>{STATE.title}</H1>
        <Row gap={8} align="center">
          <Stat label="Modules" value={String(STATE.totalModules)} />
          <Stat label="Categories" value={String(STATE.categories.length)} />
        </Row>
        <Text tone="secondary" size="small">{STATE.generatedAt}</Text>
      </Stack>

      <Divider />

      {STATE.categories.map((group) => (
        <Stack key={group.category} gap={10}>
          <Row gap={8} align="center">
            <H2>{group.category}</H2>
            <Pill tone="neutral">{group.count}</Pill>
          </Row>
          <Text tone="secondary">{group.description}</Text>
          <Table
            headers={['Module', 'Summary', 'Tags']}
            rows={group.modules.map((mod) => [
              mod.name,
              mod.summary,
              (mod.tags || []).join(', ') || '—'
            ])}
          />
        </Stack>
      ))}
    </Stack>
  );
}
