/* AUTO-GENERATED by @rtp/canvas-core — kind: platform
 * Regenerate with: ./rtpsc canvas create platform
 * Do not hand-edit the STATE literal; template body may be customized carefully.
 */
import {
  Card,
  CardBody,
  CardHeader,
  Divider,
  Grid,
  H1,
  H2,
  Pill,
  Row,
  Stack,
  Stat,
  Table,
  Text
} from 'cursor/canvas';

const STATE = {
  "kind": "platform",
  "title": "RTPSC Platform Constellation",
  "company": "Ross Tax Pro Software Co",
  "application": "Efile Transmission Software",
  "abbreviation": "RTPSC",
  "generatedAt": "2026-07-26T08:47:34.487Z",
  "totalModules": 34,
  "categoryCounts": [
    {
      "category": "packages",
      "count": 13
    },
    {
      "category": "services",
      "count": 8
    },
    {
      "category": "workers",
      "count": 4
    },
    {
      "category": "pipelines",
      "count": 3
    },
    {
      "category": "engines",
      "count": 3
    },
    {
      "category": "workflows",
      "count": 3
    }
  ],
  "environment": {
    "appEnv": "local",
    "protected": true,
    "transmissionAllowed": false,
    "safeguards": {
      "productionEnvironment": false,
      "secretsConfigured": false,
      "approvedTunnel": false,
      "transmissionFlagEnabled": false
    },
    "reasons": [
      "Environment \"local\" is not a production environment.",
      "API/TDS/tunnel secrets are not fully configured.",
      "No approved secure tunnel endpoint is configured.",
      "EFILE_TRANSMISSION_ENABLED is not set to \"true\"."
    ]
  },
  "workflowCount": 3,
  "workflows": [
    {
      "name": "refund-status-update",
      "trigger": "event",
      "description": "Normalize a refund request, evaluate status, score risk, and emit an update event."
    },
    {
      "name": "transcript-intake",
      "trigger": "manual",
      "description": "Validate authorization, normalize transcript products, and package a TDS packet."
    },
    {
      "name": "transmission-cycle",
      "trigger": "schedule",
      "description": "Prepare, validate, queue, transmit (stub-safe), and acknowledge a transmission batch."
    }
  ]
} as const;

function toneForProtected(value: boolean): 'warning' | 'success' {
  return value ? 'warning' : 'success';
}

export default function PlatformCanvas() {
  const envLabel = STATE.environment.transmissionAllowed ? 'TRANSMIT CLEAR' : 'PROTECTED';
  return (
    <Stack gap={20} style={{ padding: 24 }}>
      <Stack gap={6}>
        <Text tone="secondary" size="small">{STATE.company}</Text>
        <H1>{STATE.title}</H1>
        <Row gap={8} align="center">
          <Pill tone={toneForProtected(STATE.environment.protected)}>{envLabel}</Pill>
          <Text tone="secondary" size="small">
            {STATE.application} · generated {STATE.generatedAt}
          </Text>
        </Row>
      </Stack>

      <Grid columns={4} gap={12}>
        <Stat label="Modules" value={String(STATE.totalModules)} />
        <Stat label="Categories" value={String(STATE.categoryCounts.length)} />
        <Stat label="Workflows" value={String(STATE.workflowCount)} />
        <Stat label="App env" value={String(STATE.environment.appEnv)} />
      </Grid>

      <Divider />

      <Stack gap={12}>
        <H2>Categories</H2>
        <Table
          headers={['Category', 'Count']}
          rows={STATE.categoryCounts.map((c) => [c.category, String(c.count)])}
        />
      </Stack>

      <Stack gap={12}>
        <H2>Environment protection</H2>
        {STATE.environment.reasons.length === 0 ? (
          <Text>All transmission safeguards currently pass.</Text>
        ) : (
          <Stack gap={6}>
            {STATE.environment.reasons.map((reason, index) => (
              <Text key={index}>• {reason}</Text>
            ))}
          </Stack>
        )}
      </Stack>

      <Stack gap={12}>
        <H2>Workflows</H2>
        <Table
          headers={['Name', 'Trigger', 'Description']}
          rows={STATE.workflows.map((wf) => [wf.name, String(wf.trigger), wf.description || '—'])}
        />
      </Stack>
    </Stack>
  );
}
