/**
 * Cursor Canvas React templates.
 *
 * Generated files import only from `cursor/canvas` (+ React). They render in the
 * Cursor IDE Agents Window; they are not a runtime product dependency.
 */

function banner(kindId) {
  return `/* AUTO-GENERATED by @rtp/canvas-core — kind: ${kindId}
 * Regenerate with: ./rtpsc canvas create ${kindId}
 * Do not hand-edit the STATE literal; template body may be customized carefully.
 */`;
}

const SHARED_IMPORTS = `import {
  Card,
  CardBody,
  CardHeader,
  Divider,
  Grid,
  H1,
  H2,
  Pill,
  Row,
  Stack,
  Stat,
  Table,
  Text
} from 'cursor/canvas';`;

export function renderCanvasSource(kindId, state) {
  const stateLiteral = JSON.stringify(state, null, 2);
  const body = BODY_FOR[kindId];
  if (!body) throw new Error(`No canvas template for kind: ${kindId}`);
  return `${banner(kindId)}\n${SHARED_IMPORTS}\n\nconst STATE = ${stateLiteral} as const;\n\n${body}\n`;
}

const PLATFORM_BODY = `function toneForProtected(value: boolean): 'warning' | 'success' {
  return value ? 'warning' : 'success';
}

export default function PlatformCanvas() {
  const envLabel = STATE.environment.transmissionAllowed ? 'TRANSMIT CLEAR' : 'PROTECTED';
  return (
    <Stack gap={20} style={{ padding: 24 }}>
      <Stack gap={6}>
        <Text tone="secondary" size="small">{STATE.company}</Text>
        <H1>{STATE.title}</H1>
        <Row gap={8} align="center">
          <Pill tone={toneForProtected(STATE.environment.protected)}>{envLabel}</Pill>
          <Text tone="secondary" size="small">
            {STATE.application} · generated {STATE.generatedAt}
          </Text>
        </Row>
      </Stack>

      <Grid columns={4} gap={12}>
        <Stat label="Modules" value={String(STATE.totalModules)} />
        <Stat label="Categories" value={String(STATE.categoryCounts.length)} />
        <Stat label="Workflows" value={String(STATE.workflowCount)} />
        <Stat label="App env" value={String(STATE.environment.appEnv)} />
      </Grid>

      <Divider />

      <Stack gap={12}>
        <H2>Categories</H2>
        <Table
          headers={['Category', 'Count']}
          rows={STATE.categoryCounts.map((c) => [c.category, String(c.count)])}
        />
      </Stack>

      <Stack gap={12}>
        <H2>Environment protection</H2>
        {STATE.environment.reasons.length === 0 ? (
          <Text>All transmission safeguards currently pass.</Text>
        ) : (
          <Stack gap={6}>
            {STATE.environment.reasons.map((reason, index) => (
              <Text key={index}>• {reason}</Text>
            ))}
          </Stack>
        )}
      </Stack>

      <Stack gap={12}>
        <H2>Workflows</H2>
        <Table
          headers={['Name', 'Trigger', 'Description']}
          rows={STATE.workflows.map((wf) => [wf.name, String(wf.trigger), wf.description || '—'])}
        />
      </Stack>
    </Stack>
  );
}`;

const COMPLIANCE_BODY = `function gateTone(status: string): 'neutral' | 'info' | 'success' | 'warning' | 'danger' {
  switch (status) {
    case 'clear':
    case 'configured':
    case 'enforced':
      return 'success';
    case 'ready_scaffold':
    case 'scaffold':
      return 'info';
    case 'blocked':
      return 'warning';
    default:
      return 'neutral';
  }
}

export default function ComplianceCanvas() {
  return (
    <Stack gap={20} style={{ padding: 24 }}>
      <Stack gap={6}>
        <Text tone="secondary" size="small">{STATE.company}</Text>
        <H1>{STATE.title}</H1>
        <Text tone="secondary" size="small">
          Scaffold readiness · {STATE.generatedAt}
        </Text>
      </Stack>

      <Grid columns={3} gap={12}>
        <Stat label="App env" value={String(STATE.environment.appEnv)} />
        <Stat
          label="Transmission"
          value={STATE.environment.transmissionAllowed ? 'allowed' : 'blocked'}
        />
        <Stat label="Protected" value={STATE.environment.protected ? 'yes' : 'no'} />
      </Grid>

      <Divider />

      <Stack gap={12}>
        <H2>Gates</H2>
        <Grid columns={2} gap={12}>
          {STATE.gates.map((gate) => (
            <Card key={gate.id}>
              <CardHeader
                title={gate.label}
                trailing={<Pill tone={gateTone(gate.status)}>{gate.status}</Pill>}
              />
              <CardBody>
                <Text>{gate.detail}</Text>
              </CardBody>
            </Card>
          ))}
        </Grid>
      </Stack>

      <Stack gap={8}>
        <H2>Open protection reasons</H2>
        {STATE.environment.reasons.length === 0 ? (
          <Text>None.</Text>
        ) : (
          STATE.environment.reasons.map((reason, index) => (
            <Text key={index}>• {reason}</Text>
          ))
        )}
      </Stack>
    </Stack>
  );
}`;

const AGENTS_BODY = `export default function AgentsCanvas() {
  return (
    <Stack gap={20} style={{ padding: 24 }}>
      <Stack gap={6}>
        <Text tone="secondary" size="small">{STATE.company}</Text>
        <H1>{STATE.title}</H1>
        <Row gap={8} align="center">
          <Pill tone="info">{STATE.teamCount} agents</Pill>
          <Text tone="secondary" size="small">{STATE.generatedAt}</Text>
        </Row>
        <Text>{STATE.note}</Text>
      </Stack>

      <Divider />

      <Stack gap={12}>
        {STATE.team.map((member) => (
          <Card key={member.role}>
            <CardHeader title={member.title} trailing={<Pill tone="neutral">{member.role}</Pill>} />
            <CardBody>
              <Text>{member.focus}</Text>
            </CardBody>
          </Card>
        ))}
      </Stack>
    </Stack>
  );
}`;

const MODULES_BODY = `export default function ModulesCanvas() {
  return (
    <Stack gap={20} style={{ padding: 24 }}>
      <Stack gap={6}>
        <Text tone="secondary" size="small">{STATE.company}</Text>
        <H1>{STATE.title}</H1>
        <Row gap={8} align="center">
          <Stat label="Modules" value={String(STATE.totalModules)} />
          <Stat label="Categories" value={String(STATE.categories.length)} />
        </Row>
        <Text tone="secondary" size="small">{STATE.generatedAt}</Text>
      </Stack>

      <Divider />

      {STATE.categories.map((group) => (
        <Stack key={group.category} gap={10}>
          <Row gap={8} align="center">
            <H2>{group.category}</H2>
            <Pill tone="neutral">{group.count}</Pill>
          </Row>
          <Text tone="secondary">{group.description}</Text>
          <Table
            headers={['Module', 'Summary', 'Tags']}
            rows={group.modules.map((mod) => [
              mod.name,
              mod.summary,
              (mod.tags || []).join(', ') || '—'
            ])}
          />
        </Stack>
      ))}
    </Stack>
  );
}`;

const BODY_FOR = {
  platform: PLATFORM_BODY,
  compliance: COMPLIANCE_BODY,
  agents: AGENTS_BODY,
  modules: MODULES_BODY
};
