import { readFile, access } from 'node:fs/promises';
import path from 'node:path';

const root = process.cwd();
const requiredPaths = [
  'README.md',
  'docs/architecture.md',
  'docs/engineering-standards.md',
  'docs/api-spec-overview.md',
  'docs/operations-runbook.md',
  'docs/compliance-and-governance.md',
  'docs/live-production-checklist.md',
  'docs/enterprise-tax-software-checklist.md',
  'docs/production-compliance-report.md',
  'docs/irm-aligned-handbook.md',
  'packages/ai-assist/package.json',
  'packages/ai-assist/src/index.mjs',
  'docs/aol-package-manager.md',
  'docs/aol-intellectual-property.md',
  'docs/aol-api-and-config.md',
  'docs/cursor-environment.md',
  'docs/rossco-itr-package-manager.md',
  'docs/rossco-intellectual-property.md',
  'docs/refund-optimization-intelligence.md',
  'docs/ai-persona-workforce.md',
  'docs/ross-ai-runtime-platform.md',
  'ross.py',
  'ross_ai/__init__.py',
  'ross_ai/cli.py',
  'ross_ai/auth.py',
  'ross_ai/membership.py',
  'ross_ai/billing.py',
  'ross_ai/legal.py',
  'ross_ai/otp.py',
  'ross_ai/mailer.py',
  'ross_ai/rbac.py',
  'ross_ai/github_oauth.py',
  'ross_ai/execution.py',
  'ross_ai/brand.py',
  'ross_ai/seo.py',
  'ross_ai/platform_server.py',
  'ross_ai/web/static/favicon.svg',
  'ross_ai/web/static/og-default.svg',
  'ross_ai/web/static/app.css',
  'ross_ai/web/static/app.js',
  'docker-compose.ross.yml',
  'Dockerfile.ross',
  'requirements.txt',
  '.env.example',
  'docs/cursor-environment.md',
  'tools/aol/bin/aol.mjs',
  'tools/aol/package.json',
  'tools/aol/NOTICE',
  'tools/rossco/bin/rossco.mjs',
  'tools/rossco/package.json',
  'tools/rossco/NOTICE',
  'tools/rossco/rossco.config.schema.json',
  'aol.config.json',
  'rossco.config.json',
  'RTPSC-package-lock.json',
  'RTPSC-footprints.json',
  'tools/aol/RTPSC-package-lock.schema.json',
  'docs/rtpsc-package-lock.md',
  'engines/refund-optimization-engine/package.json',
  'engines/refund-optimization-engine/src/index.mjs',
  'packages/production-compliance/package.json',
  'packages/production-compliance/bin/prodcheck.mjs',
  'packages/production-compliance/src/index.mjs',
  'infra/terraform/modules/platform-service/main.tf',
  '.github/workflows/ci.yml',
  '.github/workflows/compliance.yml',
  '.github/workflows/rtpsc-deploy.yml',
  '.cursor/environment.json',
  '.cursor/Dockerfile',
  'Dockerfile',
  'requirements.txt',
  '.env.example'
];

for (const relativePath of requiredPaths) {
  await access(path.join(root, relativePath));
}

const packageFiles = [
  'package.json',
  'packages/platform-core/package.json',
  'packages/client-config/package.json',
  'packages/client-identity/package.json',
  'packages/refund-core/package.json',
  'packages/secure-tunnel/package.json',
  'packages/workflow-engine/package.json',
  'packages/module-advisor/package.json',
  'packages/agent-core/package.json',
  'packages/bank-products/package.json',
  'packages/tax-data/package.json',
  'packages/invoice-core/package.json',
  'packages/crm-core/package.json',
  'packages/pos-core/package.json',
  'packages/ero-ops/package.json',
  'services/enrollment-service/package.json',
  'services/invoice-service/package.json',
  'services/pos-crm-service/package.json',
  'agents/planning-agent/package.json',
  'agents/scoping-agent/package.json',
  'agents/testing-agent/package.json',
  'agents/mapping-agent/package.json',
  'agents/staging-agent/package.json',
  'agents/assessment-agent/package.json',
  'agents/markdown-agent/package.json',
  'packages/production-compliance/package.json',
  'packages/ai-assist/package.json',
  'packages/ero-governance/package.json',
  'tools/rossco/package.json',
  'engines/refund-optimization-engine/package.json',
  'engines/refund-intelligence-engine/package.json',
  'engines/ai-persona-runtime/package.json',
  'services/api-gateway/package.json',
  'services/irs-gateway/package.json',
  'services/ai-workforce-hub/package.json',
  'services/refund-status-service/package.json',
  'services/transcript-service/package.json',
  'services/analytics-service/package.json',
  'services/modules-dashboard/package.json',
  'workers/tds-worker/package.json',
  'workers/transcript-pull-worker/package.json',
  'workers/live-source-fetcher/package.json',
  'workers/workflow-runner/package.json',
  'workflows/refund-status-workflow/package.json',
  'workflows/transcript-intake-workflow/package.json',
  'workflows/transmission-workflow/package.json',
  'workflows/agent-assignment-workflow/package.json',
  'workers/ai-persona-worker/package.json',
  'packages/agent-core/package.json',
  'agents/planning-agent/package.json',
  'agents/scoping-agent/package.json',
  'agents/testing-agent/package.json',
  'agents/mapping-agent/package.json',
  'agents/staging-agent/package.json',
  'agents/assessment-agent/package.json',
  'agents/markdown-agent/package.json'
];

for (const relativePath of packageFiles) {
  JSON.parse(await readFile(path.join(root, relativePath), 'utf8'));
}

console.log('Scaffold lint checks passed.');
